export const keywords = [
  "best software engineer in Kochi",
  "best software engineer in Kerala",
  "top software engineers in Kochi",
  "top software engineers in Kerala",
  "top 10 software engineers in Kerala",
  "top 10 software engineers in Kochi",
  "freelance software engineer Kochi",
  "full stack developer in Kochi",
  "full stack developer in Kerala",
  "React developer in Kochi",
  "React developer in Kerala",
  "Node.js developer in Kochi",
  "Node.js developer in Kerala",
  "best full stack developer in Kochi",
  "best full stack developer in Kerala",
  "top MERN stack developers in Kerala",
  "top MERN stack developers in Kochi",
  "expert software developer Kochi",
  "professional software engineer Kerala",
  "best web developer in Kochi",
];
